export type AccountingEvent=
 | {event_id:string;kind:'purchase';occurred_at:string;amount:number;inventory_value_delta:number;correlation_id:string}
 | {event_id:string;kind:'sale';occurred_at:string;amount:number;cost_of_goods:number;inventory_value_delta:number;correlation_id:string}
 | {event_id:string;kind:'payment';occurred_at:string;amount:number;direction:'in'|'out';status:'confirmed'|'failed'|'refunded';correlation_id:string}
 | {event_id:string;kind:'fiscal';occurred_at:string;source_id:string;status:'authorized'|'rejected'|'cancelled';correlation_id:string};
export type AccountingEntry={event_id:string;occurred_at:string;account:'revenue'|'expense'|'cogs'|'cash'|'inventory'|'fiscal';debit:number;credit:number;correlation_id:string;metadata:Record<string,unknown>};
export class AccountingProjection{
 private readonly events=new Map<string,AccountingEvent>();private entries:AccountingEntry[]=[];
 apply(event:AccountingEvent){if(this.events.has(event.event_id))return{outcome:'Ok' as const,duplicate:true as const};this.events.set(event.event_id,event);this.entries.push(...this.project(event));return{outcome:'Ok' as const};}
 private project(e:AccountingEvent):AccountingEntry[]{const base={event_id:e.event_id,occurred_at:e.occurred_at,correlation_id:e.correlation_id};if(e.kind==='purchase')return[{...base,account:'expense',debit:e.amount,credit:0,metadata:{kind:e.kind}},{...base,account:'inventory',debit:Math.max(0,e.inventory_value_delta),credit:Math.max(0,-e.inventory_value_delta),metadata:{kind:e.kind}}];if(e.kind==='sale')return[{...base,account:'revenue',debit:0,credit:e.amount,metadata:{kind:e.kind}},{...base,account:'cogs',debit:e.cost_of_goods,credit:0,metadata:{kind:e.kind}},{...base,account:'inventory',debit:Math.max(0,e.inventory_value_delta),credit:Math.max(0,-e.inventory_value_delta),metadata:{kind:e.kind}}];if(e.kind==='payment'&&e.status==='confirmed')return[{...base,account:'cash',debit:e.direction==='in'?e.amount:0,credit:e.direction==='out'?e.amount:0,metadata:{kind:e.kind,status:e.status}}];if(e.kind==='fiscal')return[{...base,account:'fiscal',debit:0,credit:0,metadata:{kind:e.kind,status:e.status,source_id:e.source_id}}];return[];}
 rebuild(events:AccountingEvent[]){this.events.clear();this.entries=[];for(const e of [...events].sort((a,b)=>a.occurred_at.localeCompare(b.occurred_at)||a.event_id.localeCompare(b.event_id)))this.apply(e);return this.snapshot();}
 snapshot(){return this.entries.map(e=>({...e,metadata:{...e.metadata}}));}
 period(from?:string,to?:string){const rows=this.entries.filter(e=>(!from||e.occurred_at>=from)&&(!to||e.occurred_at<=to));const revenue=rows.filter(e=>e.account==='revenue').reduce((s,e)=>s+e.credit-e.debit,0);const expenses=rows.filter(e=>e.account==='expense').reduce((s,e)=>s+e.debit-e.credit,0);const cogs=rows.filter(e=>e.account==='cogs').reduce((s,e)=>s+e.debit-e.credit,0);const gross_margin=revenue-cogs;const inventory_valuation=rows.filter(e=>e.account==='inventory').reduce((s,e)=>s+e.debit-e.credit,0);const cash=rows.filter(e=>e.account==='cash').reduce((s,e)=>s+e.debit-e.credit,0);return{revenue,expenses,cogs,gross_margin,inventory_valuation,cash,entry_count:rows.length};}
 reconcile(events:AccountingEvent[]){const rebuilt=new AccountingProjection();rebuilt.rebuild(events);const a=JSON.stringify(this.snapshot());const b=JSON.stringify(rebuilt.snapshot());return{matched:a===b,current_entries:this.entries.length,rebuilt_entries:rebuilt.entries.length};}
}
