import {mkdir,writeFile} from 'node:fs/promises';import {E2EProductSystem} from '../runtime/e2e-product-system.js';
const scenarios:Array<{name:string;passed:boolean;evidence:unknown}>=[];
function record(name:string,run:()=>{passed:boolean;evidence?:unknown}){const r=run();scenarios.push({name,passed:r.passed,evidence:r.evidence??null});}
record('purchase-whatsapp-audio-receipt',()=>{const s=new E2EProductSystem();s.purchaseFromWhatsApp({message_id:'m1',conversation_id:'p1',audio_text:'6 beer',receipt:{supplier:'Market',items:[{name:'beer',quantity:6,unit_price:4}]}});return{passed:s.state.products.beer?.stock===16&&s.state.financial.expense===24,evidence:s.evidence};});
record('sale-detected-conversation-resolution',()=>{const s=new E2EProductSystem();s.detectSale({provider_event_id:'pay',sale_id:'s1',amount:12});s.answerSale({message_id:'answer',sale_id:'s1',products:[{name:'beer',quantity:2}]});return{passed:s.state.sales.s1?.status==='closed'&&s.state.products.beer?.stock===8&&s.state.financial.income===12,evidence:s.evidence};});
record('healing-human-resume',()=>{const s=new E2EProductSystem();s.purchaseFromWhatsApp({message_id:'a',conversation_id:'p2',audio_text:'?',receipt:{supplier:'M',items:[]}});s.confirmHuman({message_id:'c',conversation_id:'p2',correction:{receipt:{supplier:'M',items:[{name:'water',quantity:2,unit_price:3}]}}});return{passed:s.uiProjection().healing.length===0&&s.state.products.water?.stock===2};});
record('duplicate-idempotency',()=>{const s=new E2EProductSystem();const p={message_id:'dup',conversation_id:'p3',audio_text:'1 beer',receipt:{supplier:'M',items:[{name:'beer',quantity:1,unit_price:4}]}};s.purchaseFromWhatsApp(p);s.purchaseFromWhatsApp(p);return{passed:s.state.products.beer?.stock===11&&s.state.financial.expense===4};});
record('restart-resume',()=>{let s=new E2EProductSystem();s.detectSale({provider_event_id:'r-pay',sale_id:'r-sale',amount:5});s=s.restart();s.answerSale({message_id:'r-answer',sale_id:'r-sale',products:[{name:'beer',quantity:1}]});return{passed:s.state.sales['r-sale']?.status==='closed'&&s.state.idempotency.has('r-pay')&&s.state.idempotency.has('r-answer')};});
const result={suite:'v1-e2e-product-acceptance',generated_at:new Date().toISOString(),passed:scenarios.every(x=>x.passed),scenarios};await mkdir('reports/e2e',{recursive:true});await writeFile('reports/e2e/result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));if(!result.passed)process.exitCode=1;
