export type CustomerProfile={customer_id:string;name:string;phone?:string;whatsapp_id?:string;email?:string;created_at:string;updated_at:string};
export type CustomerAccessContext={capabilities:string[]};
export type CustomerSaleLink={customer_id:string;sale_id:string;payment_id?:string;amount:number;occurred_at:string};
export interface CustomerPrivacyPolicyPort{canReadSensitive(context:CustomerAccessContext,field:'phone'|'whatsapp_id'|'email'):boolean|Promise<boolean>;}
export class CustomerManagement{
 private readonly customers=new Map<string,CustomerProfile>();private readonly identity=new Map<string,string>();private readonly links:CustomerSaleLink[]=[];
 constructor(private readonly privacy:CustomerPrivacyPolicyPort){}
 private keys(input:{phone?:string;whatsapp_id?:string;email?:string}){return [input.phone&&`phone:${input.phone}`,input.whatsapp_id&&`wa:${input.whatsapp_id}`,input.email&&`email:${input.email.toLowerCase()}`].filter((v):v is string=>Boolean(v));}
 create(input:Omit<CustomerProfile,'customer_id'|'created_at'|'updated_at'>){const duplicate=this.keys(input).map(k=>this.identity.get(k)).find(Boolean);if(duplicate)return{outcome:'Ok' as const,customer:{...this.customers.get(duplicate)!},duplicate:true as const};const now=new Date().toISOString();const customer:{customer_id:string}&Omit<CustomerProfile,'customer_id'>={customer_id:`cus-${this.customers.size+1}`,...input,created_at:now,updated_at:now};this.customers.set(customer.customer_id,customer);for(const k of this.keys(customer))this.identity.set(k,customer.customer_id);return{outcome:'Ok' as const,customer:{...customer}};}
 update(customer_id:string,patch:Partial<Pick<CustomerProfile,'name'|'phone'|'whatsapp_id'|'email'>>){const current=this.customers.get(customer_id);if(!current)return{outcome:'Error' as const,code:'CustomerNotFound' as const};for(const k of this.keys(patch)){const owner=this.identity.get(k);if(owner&&owner!==customer_id)return{outcome:'Error' as const,code:'DuplicateIdentity' as const};}const previous=this.keys(current);const next={...current,...patch,updated_at:new Date().toISOString()};this.customers.set(customer_id,next);for(const k of previous)if(this.identity.get(k)===customer_id)this.identity.delete(k);for(const k of this.keys(next))this.identity.set(k,customer_id);return{outcome:'Ok' as const,customer:{...next}};}
 search(text:string){const q=text.trim().toLowerCase();return [...this.customers.values()].filter(c=>!q||c.name.toLowerCase().includes(q)||c.customer_id.toLowerCase().includes(q)).map(c=>({...c,phone:undefined,whatsapp_id:undefined,email:undefined}));}
 async get(customer_id:string,context:CustomerAccessContext){const c=this.customers.get(customer_id);if(!c)return undefined;const out:{customer_id:string;name:string;created_at:string;updated_at:string;phone?:string;whatsapp_id?:string;email?:string}={customer_id:c.customer_id,name:c.name,created_at:c.created_at,updated_at:c.updated_at};for(const field of ['phone','whatsapp_id','email'] as const)if(c[field]!==undefined&&await this.privacy.canReadSensitive(context,field))out[field]=c[field];return out;}
 linkSale(input:CustomerSaleLink){if(!this.customers.has(input.customer_id))return{outcome:'Error' as const,code:'CustomerNotFound' as const};if(this.links.some(l=>l.sale_id===input.sale_id&&l.customer_id===input.customer_id))return{outcome:'Ok' as const,duplicate:true as const};this.links.push({...input});return{outcome:'Ok' as const};}
 history(customer_id:string){return this.links.filter(l=>l.customer_id===customer_id).map(l=>({...l})).sort((a,b)=>a.occurred_at.localeCompare(b.occurred_at));}
 summary(customer_id:string){const h=this.history(customer_id);return{purchase_count:h.length,total:h.reduce((s,x)=>s+x.amount,0),last_interaction:h.at(-1)?.occurred_at};}
}
