export type Supplier={supplier_id:string;name:string;tax_id?:string;phone?:string;whatsapp?:string;email?:string;created_at:string;updated_at:string};
export type SupplierPurchase={purchase_id:string;supplier_id:string;product_ids:string[];amount:number;occurred_at:string;expense_id?:string};
export type SupplierEvidence={name?:string;tax_id?:string;phone?:string;whatsapp?:string;email?:string};
const norm=(v:string)=>v.trim().toLowerCase();const digits=(v:string)=>v.replace(/\D/g,'');
export class SupplierManagement{
 private suppliers=new Map<string,Supplier>();private identities=new Map<string,string>();private purchases:SupplierPurchase[]=[];private seq=0;
 private keys(v:SupplierEvidence){const k:string[]=[];if(v.tax_id)k.push(`tax:${digits(v.tax_id)}`);if(v.phone)k.push(`phone:${digits(v.phone)}`);if(v.whatsapp)k.push(`wa:${digits(v.whatsapp)}`);if(v.email)k.push(`email:${norm(v.email)}`);return k;}
 private findIdentity(v:SupplierEvidence){for(const k of this.keys(v)){const id=this.identities.get(k);if(id)return id;}return undefined;}
 private index(s:Supplier){for(const k of this.keys(s))this.identities.set(k,s.supplier_id);}
 create(input:{name:string;tax_id?:string;phone?:string;whatsapp?:string;email?:string;now:string}){const duplicate=this.findIdentity(input);if(duplicate)return{outcome:'Ok' as const,supplier:this.suppliers.get(duplicate)!,duplicate:true as const};const supplier:Supplier={supplier_id:`supplier-${++this.seq}`,name:input.name.trim(),created_at:input.now,updated_at:input.now,...(input.tax_id?{tax_id:input.tax_id}:{}),...(input.phone?{phone:input.phone}:{}),...(input.whatsapp?{whatsapp:input.whatsapp}:{}),...(input.email?{email:input.email}: {})};this.suppliers.set(supplier.supplier_id,supplier);this.index(supplier);return{outcome:'Ok' as const,supplier:{...supplier}};}
 update(id:string,patch:SupplierEvidence&{name?:string;now:string}){const current=this.suppliers.get(id);if(!current)return{outcome:'Error' as const,code:'SupplierNotFound' as const};const collision=this.findIdentity(patch);if(collision&&collision!==id)return{outcome:'Error' as const,code:'IdentityConflict' as const};const next:Supplier={...current,...patch,updated_at:patch.now};this.suppliers.set(id,next);this.index(next);return{outcome:'Ok' as const,supplier:{...next}};}
 resolveFromEvidence(evidence:SupplierEvidence&{now:string}){const id=this.findIdentity(evidence);if(id)return{outcome:'Ok' as const,supplier:{...this.suppliers.get(id)!},resolved:true as const};if(!evidence.name)return{outcome:'Error' as const,code:'InsufficientSupplierEvidence' as const};return this.create({...evidence,name:evidence.name,now:evidence.now});}
 search(q:string){const n=norm(q),d=digits(q);return[...this.suppliers.values()].filter(s=>norm(s.name).includes(n)||(s.tax_id&&digits(s.tax_id).includes(d))||(s.email&&norm(s.email).includes(n))).map(s=>({...s}));}
 linkPurchase(input:SupplierPurchase){if(!this.suppliers.has(input.supplier_id))return{outcome:'Error' as const,code:'SupplierNotFound' as const};if(!Number.isFinite(input.amount)||input.amount<=0)return{outcome:'Error' as const,code:'InvalidAmount' as const};if(this.purchases.some(p=>p.purchase_id===input.purchase_id))return{outcome:'Ok' as const,duplicate:true as const};this.purchases.push({...input,product_ids:[...input.product_ids]});return{outcome:'Ok' as const};}
 history(id:string){return this.purchases.filter(p=>p.supplier_id===id).sort((a,b)=>b.occurred_at.localeCompare(a.occurred_at)).map(p=>({...p,product_ids:[...p.product_ids]}));}
 summary(id:string){const h=this.history(id);return{purchase_count:h.length,total_purchased:h.reduce((s,p)=>s+p.amount,0),last_purchase_at:h[0]?.occurred_at??null,last_purchase_amount:h[0]?.amount??null,product_ids:[...new Set(h.flatMap(p=>p.product_ids))]};}
 historicalProductCost(id:string,productId:string){const h=this.history(id).filter(p=>p.product_ids.includes(productId));return{last_purchase_at:h[0]?.occurred_at??null,last_purchase_amount:h[0]?.amount??null,purchase_count:h.length};}
}
