import test from 'node:test';import assert from 'node:assert/strict';import {MemoryDraftStore,OfflineResilienceCoordinator,renderConnectivityBanner} from '../ui/offline-resilience.js';import {renderAppShell} from '../ui/shell.js';

test('shell exposes primary keyboard and screen-reader landmarks',()=>{const html=renderAppShell({title:'Vendas',active:'sales',content:'<button>Salvar</button>'});for(const token of ['lang="pt-BR"','class="skip-link"','href="#main"','aria-label="Navegação principal"','aria-current="page"','tabindex="-1"'])assert.match(html,new RegExp(token));});

test('offline draft survives connectivity loss',async()=>{const store=new MemoryDraftStore();let online=false;const refreshed:string[]=[];const coordinator=new OfflineResilienceCoordinator(store,{isOnline:()=>online},{refresh:async view=>{refreshed.push(view);}},()=> '2026-08-26T14:20:00Z');await coordinator.preserveDraft('sale:resolve',{products:['water']});assert.deepEqual((await coordinator.restoreDraft<any>('sale:resolve'))?.value,{products:['water']});assert.equal(coordinator.canSubmitCriticalMutation('idem-1'),false);online=true;assert.equal(coordinator.canSubmitCriticalMutation('idem-1'),true);coordinator.markCriticalMutationSubmitted('idem-1');assert.equal(coordinator.canSubmitCriticalMutation('idem-1'),false);});

test('reconnect refreshes stale projections once without replaying mutations',async()=>{let online=true;const refreshed:string[]=[];const coordinator=new OfflineResilienceCoordinator(new MemoryDraftStore(),{isOnline:()=>online},{refresh:async view=>{refreshed.push(view);}});coordinator.markProjectionStale('SalesProjection');coordinator.markProjectionStale('InventoryProjection');assert.deepEqual((await coordinator.reconnect()).refreshed,['SalesProjection','InventoryProjection']);assert.deepEqual((await coordinator.reconnect()).refreshed,[]);assert.deepEqual(refreshed,['SalesProjection','InventoryProjection']);});

test('connectivity banner announces offline preservation',()=>{assert.match(renderConnectivityBanner({online:false,hasUnsavedDraft:true}),/aria-live="polite"/);assert.match(renderConnectivityBanner({online:false,hasUnsavedDraft:true}),/dados digitados permanecem salvos/);assert.equal(renderConnectivityBanner({online:true,hasUnsavedDraft:false}),'');});

test('styles include focus reduced-motion and mobile behavior',async()=>{const fs=await import('node:fs/promises');const css=await fs.readFile(new URL('../ui/styles.css',import.meta.url),'utf8');assert.match(css,/:focus-visible/);assert.match(css,/prefers-reduced-motion/);assert.match(css,/max-width:760px/);assert.match(css,/min-height:44px/);assert.match(css,/overflow-wrap:anywhere/);});