import test from 'node:test';import assert from 'node:assert/strict';
import {AdministrationSettingsUi} from '../ui/administration-settings.js';

function harness(){const calls:any[]=[];const api:any={query:(...args:any[])=>{calls.push(['query',...args]);return Promise.resolve({outcome:'Ok',data:{}});},command:(...args:any[])=>{calls.push(['command',...args]);return Promise.resolve({outcome:'Ok',data:{}});}};return{ui:new AdministrationSettingsUi(api),calls};}

test('administration reads only explicit projections',async()=>{const h=harness();await h.ui.profile('c1');await h.ui.integrations('c2');await h.ui.users('c3');await h.ui.operationalSettings('c4');await h.ui.auditTrail('c5');assert.deepEqual(h.calls.map(c=>c[1]),['BusinessProfileProjection','IntegrationStatusProjection','UsersRolesProjection','OperationalSettingsProjection','ConfigurationAuditProjection']);});

test('configuration writes are intent boundaries with separate activation',async()=>{const h=harness();await h.ui.saveProfile({name:'Bar',timezone:'America/Sao_Paulo',currency:'BRL'},'c1','i1');await h.ui.saveOperationalSettings({minimum_stock_default:5,notification_preferences:{healing_required:true,low_stock:true,payment_failed:true}},'c2','i2');await h.ui.saveUserRole({user_id:'u1',role:'manager',status:'active'},'c3','i3');await h.ui.saveIntegrationConfig({provider:'evolution-go',enabled:true,config:{instance:'bar'}},'c4','i4');await h.ui.activateConfiguration({scope:'business',version:'v2'},'c5','i5');assert.deepEqual(h.calls.map(c=>c[1]),['UpdateBusinessProfileIntent','UpdateOperationalSettingsIntent','UpdateUserRoleIntent','UpdateIntegrationConfigIntent','ActivateValidatedConfigurationIntent']);});

test('secret editor is write-only and never pre-populates stored material',()=>{const h=harness();const html=h.ui.renderSecretEditor('evolution-go','apikey');assert.match(html,/type="password"/);assert.match(html,/value=""/);assert.match(html,/write-only/i);assert.doesNotMatch(html,/stored-secret|existing-secret|secret_value="[^\"]+"/);});

test('profile preserves input when semantic validation rejects change',()=>{const h=harness();const html=h.ui.renderProfile({kind:'ready',profile:{name:'Bar Central',timezone:'America/Sao_Paulo',currency:'BRL'},result:{outcome:'Error',correlation_id:'c',error:{code:'validation',message:'documento inválido'}} as any});assert.match(html,/data-preserve-input="true"/);assert.match(html,/Bar Central/);assert.match(html,/documento inválido/);});

test('integration status and operational thresholds are rendered from projections',()=>{const h=harness();const integrations=h.ui.renderIntegrations([{provider:'evolution-go',channel:'whatsapp',status:'connected',configured:true,last_check_at:'10:00'}]);assert.match(integrations,/evolution-go/);assert.match(integrations,/connected/);const settings=h.ui.renderOperationalSettings({minimum_stock_default:7,notification_preferences:{healing_required:true,low_stock:false,payment_failed:true}});assert.match(settings,/value="7"/);assert.match(settings,/healing_required" checked/);});