import test from 'node:test';import assert from 'node:assert/strict';
import {E2EProductSystem,createPersistedState} from '../runtime/e2e-product-system.js';

test('purchase audio plus receipt reaches stock financial and UI projection',()=>{const s=new E2EProductSystem();s.purchaseFromWhatsApp({message_id:'m1',conversation_id:'purchase-1',audio_text:'comprei 6 cervejas',receipt:{supplier:'Mercado Central',items:[{name:'beer',quantity:6,unit_price:4}]}});const ui=s.uiProjection();assert.equal(ui.inventory.find(x=>x.product==='beer')?.stock,16);assert.equal(ui.financial.expense,24);assert.equal(ui.purchases[0]?.supplier,'Mercado Central');assert.ok(s.evidence.some(e=>e.scenario==='purchase'));});

test('detected payment asks for products then closes sale and updates stock financial and UI',()=>{const s=new E2EProductSystem();s.detectSale({provider_event_id:'pay-1',sale_id:'sale-1',amount:12});assert.equal(s.uiProjection().healing[0]?.kind,'sale');s.answerSale({message_id:'msg-sale-answer',sale_id:'sale-1',products:[{name:'beer',quantity:2}]});const ui=s.uiProjection();assert.equal(ui.sales[0]?.status,'closed');assert.equal(ui.inventory.find(x=>x.product==='beer')?.stock,8);assert.equal(ui.financial.income,12);});

test('ambiguous purchase enters healing and human correction resumes intent without manual database changes',()=>{const s=new E2EProductSystem();s.purchaseFromWhatsApp({message_id:'amb-1',conversation_id:'purchase-h',audio_text:'não entendi',receipt:{supplier:'Mercado',items:[]}});assert.equal(s.uiProjection().healing.length,1);s.confirmHuman({message_id:'confirm-1',conversation_id:'purchase-h',correction:{audio_text:'6 águas a 2',receipt:{supplier:'Mercado',items:[{name:'water',quantity:6,unit_price:2}]}}});const ui=s.uiProjection();assert.equal(ui.healing.length,0);assert.equal(ui.inventory.find(x=>x.product==='water')?.stock,6);assert.equal(ui.financial.expense,12);});

test('duplicate webhook and duplicate provider event never duplicate stock or financial effects',()=>{const s=new E2EProductSystem();const p={message_id:'dup',conversation_id:'purchase-d',audio_text:'2 cervejas',receipt:{supplier:'M',items:[{name:'beer',quantity:2,unit_price:5}]}};s.purchaseFromWhatsApp(p);s.purchaseFromWhatsApp(p);assert.equal(s.state.products.beer?.stock,12);assert.equal(s.state.financial.expense,10);s.detectSale({provider_event_id:'provider-x',sale_id:'sale-d',amount:5});s.detectSale({provider_event_id:'provider-x',sale_id:'sale-d',amount:5});s.answerSale({message_id:'sale-answer-d',sale_id:'sale-d',products:[{name:'beer',quantity:1}]});s.answerSale({message_id:'sale-answer-d',sale_id:'sale-d',products:[{name:'beer',quantity:1}]});assert.equal(s.state.products.beer?.stock,11);assert.equal(s.state.financial.income,5);});

test('restart preserves conversation idempotency events and resumes without corruption',()=>{const state=createPersistedState();let s=new E2EProductSystem(state);s.detectSale({provider_event_id:'restart-pay',sale_id:'restart-sale',amount:9});const before=[...state.events];s=s.restart();s.answerSale({message_id:'restart-answer',sale_id:'restart-sale',products:[{name:'beer',quantity:1}]});assert.equal(s.state.sales['restart-sale']?.status,'closed');assert.equal(s.state.financial.income,9);assert.equal(s.state.products.beer?.stock,9);assert.equal(before.length,1);assert.equal(s.state.events.length,2);assert.ok(s.state.idempotency.has('restart-pay'));assert.ok(s.state.idempotency.has('restart-answer'));});
