import test from 'node:test';import assert from 'node:assert/strict';
import {FinancialReportingUi,type CashFlowProjection,type ManagementReport} from '../ui/financial-reporting.js';

function harness(){const calls:any[]=[];const api:any={query:(...args:any[])=>{calls.push(['query',...args]);return Promise.resolve({outcome:'Ok',data:{}});},command:(...args:any[])=>{calls.push(['command',...args]);return Promise.resolve({outcome:'Ok',data:{}});}};return{ui:new FinancialReportingUi(api),calls};}

test('financial reads use backend projections',async()=>{const h=harness();const filters={from:'2026-08-01',to:'2026-08-26'};await h.ui.cashFlow(filters,'c1');await h.ui.reconciliation(filters,'c2');await h.ui.report('margin',filters,'c3');assert.deepEqual(h.calls.map(c=>c[1]),['CashFlowProjection','PaymentReconciliationProjection','ManagementReportProjection']);});
test('export is an explicit semantic command with selected filters',async()=>{const h=harness();const filters={from:'2026-08-01',to:'2026-08-26',provider:'pix'};await h.ui.exportReport('sales','csv',filters,'corr','idem');assert.equal(h.calls[0][1],'ExportManagementReportIntent');assert.deepEqual(h.calls[0][2],{kind:'sales',format:'csv',filters});});
test('cash flow displays projection values exactly without recomputing totals',()=>{const h=harness();const data:CashFlowProjection={period:{from:'2026-08-01',to:'2026-08-26'},currency:'BRL',revenue:1234.56,expenses:345.67,balance:888.89,opening_balance:50,closing_balance:938.89,entries:[{at:'2026-08-26',kind:'revenue',description:'Venda',amount:1234.56}]};const html=h.ui.renderCashFlow({kind:'ready',data});for(const expected of ['R$ 1.234,56','R$ 345,67','R$ 888,89','R$ 938,89'])assert.ok(html.includes(expected),expected);});
test('reconciliation exposes backend status and divergence reason',()=>{const h=harness();const html=h.ui.renderReconciliation({kind:'ready',items:[{payment_id:'p1',sale_id:'s1',at:'now',amount:20,currency:'BRL',provider:'pix',status:'divergent',reason:'valor diferente'}]});assert.match(html,/Divergente/);assert.match(html,/valor diferente/);});
test('management report renders backend totals and export controls',()=>{const h=harness();const report:ManagementReport={kind:'inventory-valuation',period:{from:'2026-08-01',to:'2026-08-26'},currency:'BRL',totals:{valuation:5000},rows:[{product:'Água',valuation:100}]};const html=h.ui.renderReport({report,headers:['product','valuation']});assert.match(html,/R$ 5.000,00/);assert.match(html,/CSV/);assert.match(html,/XLSX/);assert.match(html,/PDF/);});
test('source does not derive financial aggregates from raw records',async()=>{const fs=await import('node:fs/promises');const source=await fs.readFile(new URL('../ui/financial-reporting.ts',import.meta.url),'utf8');assert.doesNotMatch(source,/reduce\s*\(/);assert.doesNotMatch(source,/revenue\s*[-+]\s*expenses|expenses\s*[-+]\s*revenue/);assert.match(source,/ManagementReportProjection/);});