import test from 'node:test';import assert from 'node:assert/strict';
import {InventoryManagement} from '../inventory/inventory-management.js';

const policy={canAdjust:(ctx:{capabilities:string[]})=>ctx.capabilities.includes('inventory.adjust')};
function inventory(balance=10,minimum_stock=3,allow_negative=false){return new InventoryManagement(policy,[{product_id:'beer',balance,minimum_stock,allow_negative}]);}

test('balances movement history and low-stock alerts are queryable',async()=>{const i=inventory(5,4);await i.applyDomainMovement({product_id:'beer',delta:-2,kind:'sale',correlation_id:'sale:1',idempotency_key:'sale:1'});assert.equal(i.product('beer')?.balance,3);assert.equal(i.history('beer').length,1);assert.deepEqual(i.lowStockAlerts(),[{product_id:'beer',balance:3,minimum_stock:4}]);});

test('manual adjustment requires reason and explicit capability',async()=>{const i=inventory();assert.deepEqual(await i.adjust({product_id:'beer',delta:1,reason:'',correlation_id:'adjust:1',idempotency_key:'a1',context:{operator_id:'op',capabilities:['inventory.adjust']}}),{outcome:'Error',code:'ReasonRequired'});assert.deepEqual(await i.adjust({product_id:'beer',delta:1,reason:'count correction',correlation_id:'adjust:2',idempotency_key:'a2',context:{operator_id:'op',capabilities:[]}}),{outcome:'Error',code:'Unauthorized'});const ok=await i.adjust({product_id:'beer',delta:1,reason:'count correction',correlation_id:'adjust:3',idempotency_key:'a3',context:{operator_id:'op',capabilities:['inventory.adjust']}});assert.equal(ok.outcome,'Ok');assert.equal(i.product('beer')?.balance,11);assert.equal(i.history('beer')[0]?.operator_id,'op');});

test('negative stock is impossible unless product policy explicitly allows it',async()=>{const denied=inventory(1);assert.deepEqual(await denied.applyDomainMovement({product_id:'beer',delta:-2,kind:'sale',correlation_id:'sale:x',idempotency_key:'sx'}),{outcome:'Error',code:'NegativeStockForbidden'});assert.equal(denied.product('beer')?.balance,1);const allowed=inventory(1,0,true);const result=await allowed.applyDomainMovement({product_id:'beer',delta:-2,kind:'sale',correlation_id:'sale:y',idempotency_key:'sy'});assert.equal(result.outcome,'Ok');assert.equal(allowed.product('beer')?.balance,-1);});

test('idempotency prevents a duplicate mutation',async()=>{const i=inventory();const input={product_id:'beer',delta:-2,kind:'sale' as const,correlation_id:'sale:dup',idempotency_key:'dup'};const first=await i.applyDomainMovement(input);const second=await i.applyDomainMovement(input);assert.equal(first.outcome,'Ok');assert.equal(second.outcome,'Ok');assert.equal(second.outcome==='Ok'&&second.duplicate,true);assert.equal(i.product('beer')?.balance,8);assert.equal(i.history('beer').length,1);});

test('concurrent mutations on the same product are serialized without lost updates',async()=>{const i=inventory(1000,0);await Promise.all(Array.from({length:500},(_,n)=>i.applyDomainMovement({product_id:'beer',delta:-1,kind:'sale',correlation_id:`sale:${n}`,idempotency_key:`sale:${n}`})));assert.equal(i.product('beer')?.balance,500);assert.equal(i.history('beer').length,500);assert.ok(i.reconciliation().every(r=>r.consistent));});

test('inventory reconciliation reports ledger consistency',async()=>{const i=inventory(10,0);await i.applyDomainMovement({product_id:'beer',delta:5,kind:'purchase',correlation_id:'purchase:1',idempotency_key:'p1'});await i.applyDomainMovement({product_id:'beer',delta:-3,kind:'sale',correlation_id:'sale:1',idempotency_key:'s1'});const report=i.reconciliation()[0];assert.ok(report);assert.equal(report.stored_balance,12);assert.equal(report.ledger_balance,12);assert.equal(report.difference,0);assert.equal(report.consistent,true);});
