import test from 'node:test';import assert from 'node:assert/strict';
import {InMemoryExternalTransactionStore,PaymentSaleMachineIngress,type ExternalSaleTransaction} from '../integrations/payment-sale-machine/index.js';

function tx(overrides:Partial<ExternalSaleTransaction>={}):ExternalSaleTransaction{return {provider:'sandbox-terminal',transaction_id:'tx-1',amount:42.5,currency:'BRL',occurred_at:'2026-08-26T10:00:00-03:00',payment_method:'credit',status:'approved',...overrides};}
function harness(transactions:ExternalSaleTransaction[]=[]){const commands:any[]=[];const followups:any[]=[];const provider:any={provider:'sandbox-terminal',discover:async()=>({transactions,cursor:'next'}),normalizeWebhook:async(payload:any)=>[payload]};const semantic:any={command:async(...args:any[])=>{commands.push(args);return {outcome:'Ok'};}};const followUp:any={request:async(input:any)=>{followups.push(input);}};return{ingress:new PaymentSaleMachineIngress(provider,new InMemoryExternalTransactionStore(),semantic,followUp),commands,followups};}

test('approved transaction preserves provider facts and dispatches ProcessSaleIntent',async()=>{const h=harness([tx({products:[{label:'Beer',quantity:2}]})]);const cursor=await h.ingress.poll();assert.equal(cursor,'next');assert.equal(h.commands.length,1);assert.equal(h.commands[0][0],'ProcessSaleIntent');assert.deepEqual(h.commands[0][1],{provider:'sandbox-terminal',external_transaction_id:'tx-1',amount:42.5,currency:'BRL',occurred_at:'2026-08-26T10:00:00-03:00',payment_method:'credit',payment_status:'approved',products:[{label:'Beer',quantity:2}],customer_hint:undefined});assert.equal(h.commands[0][2],'payment:sandbox-terminal:tx-1');assert.equal(h.commands[0][3],'sandbox-terminal:tx-1');});

test('duplicate external transaction id is idempotent across webhook retries',async()=>{const h=harness();const payload=tx();await h.ingress.webhook(payload);await h.ingress.webhook(payload);assert.equal(h.commands.length,1);assert.equal(h.followups.length,1);});

test('unknown product composition requests follow-up after semantic sale handoff',async()=>{const h=harness([tx({products:undefined})]);await h.ingress.poll();assert.equal(h.commands[0][0],'ProcessSaleIntent');assert.equal(h.followups.length,1);assert.equal(h.followups[0].transaction.transaction_id,'tx-1');assert.equal(h.followups[0].correlation_id,'payment:sandbox-terminal:tx-1');});

test('known product composition does not create unnecessary follow-up',async()=>{const h=harness([tx({products:[{product_id:'beer',label:'Beer',quantity:1,unit_price:42.5}]})]);await h.ingress.poll();assert.equal(h.followups.length,0);});

test('refund and cancel reconcile through semantic domain intent',async()=>{for(const status of ['refunded','cancelled'] as const){const h=harness();await h.ingress.webhook(tx({transaction_id:`tx-${status}`,status}));assert.equal(h.commands[0][0],'ReconcileExternalSaleStatusIntent');assert.equal(h.followups.length,0);}});

test('pending and failed payments are observed without creating completed sales',async()=>{for(const status of ['pending','failed'] as const){const h=harness();await h.ingress.webhook(tx({transaction_id:`tx-${status}`,status}));assert.equal(h.commands[0][0],'ObserveExternalPaymentIntent');assert.equal(h.followups.length,0);}});

test('provider contract is vendor-sdk independent and supports polling plus webhook normalization',async()=>{const fs=await import('node:fs/promises');const source=await fs.readFile(new URL('../integrations/payment-sale-machine/index.ts',import.meta.url),'utf8');assert.match(source,/interface SaleMachineProviderTool/);assert.match(source,/discover\(cursor\?:string\)/);assert.match(source,/normalizeWebhook\(payload:unknown\)/);assert.doesNotMatch(source,/stripe|stone|pagseguro|mercadopago|infinitypay|sdk/i);assert.doesNotMatch(source,/inventory\.|stock\.|reduce\s*\(/);});