import test from 'node:test';import assert from 'node:assert/strict';import {ProductsInventoryUi,type ProductRow} from '../ui/products-inventory.js';

function harness(){const calls:any[]=[];const api:any={query:(projection:string,filters:any,correlationId:string,page:number,pageSize:number)=>{calls.push({kind:'query',projection,filters,correlationId,page,pageSize});return Promise.resolve({outcome:'Ok'});},command:(intent:string,payload:any,correlationId:string,idempotencyKey:string)=>{calls.push({kind:'command',intent,payload,correlationId,idempotencyKey});return Promise.resolve({outcome:'Ok'});}};return{calls,ui:new ProductsInventoryUi(api)};}

test('list search and filters are delegated to backend projection',async()=>{const h=harness();await h.ui.list({search:'agua',status:'low',category:'bebidas'},'corr-list',2,20);assert.deepEqual(h.calls[0],{kind:'query',projection:'ProductsInventoryProjection',filters:{search:'agua',status:'low',category:'bebidas'},correlationId:'corr-list',page:2,pageSize:20});});

test('movement history is loaded from inventory movements projection',async()=>{const h=harness();await h.ui.movements('water','corr-mov');assert.deepEqual(h.calls[0],{kind:'query',projection:'InventoryMovementsProjection',filters:{product_id:'water'},correlationId:'corr-mov',page:1,pageSize:50});});

test('create edit and manual adjustment are explicit intents',async()=>{const h=harness();const draft={product_id:'water',name:'Água',sku:'AGUA-500',category:'bebidas',unit:'un',minimum_stock:10,active:true};await h.ui.saveProduct('create',draft,'c1','i1');await h.ui.saveProduct('edit',draft,'c2','i2');await h.ui.adjustStock({product_id:'water',quantity:-2,reason:'avaria identificada'},'c3','i3');assert.equal(h.calls[0].intent,'CreateProductIntent');assert.equal(h.calls[1].intent,'UpdateProductMetadataIntent');assert.equal(h.calls[2].intent,'AdjustStockIntent');assert.equal(h.calls[2].payload.reason,'avaria identificada');});

test('product list renders projected stock state without local calculation',()=>{const h=harness();const items:ProductRow[]=[{product_id:'water',name:'Água',sku:'AGUA-500',category:'bebidas',unit:'un',current_stock:2,minimum_stock:10,stock_status:'low',active:true},{product_id:'beer',name:'Cerveja',current_stock:0,minimum_stock:5,stock_status:'out',active:false}];const html=h.ui.renderList({kind:'ready',items,total:2,filters:{search:'água'}});for(const text of ['Produtos e estoque','Água','Cerveja','Atual','Mínimo','Buscar','Categoria'])assert.match(html,new RegExp(text,'i'));assert.match(html,/2 produto\(s\)/);});

test('validation or healing error preserves product draft',()=>{const h=harness();const html=h.ui.renderEditor({mode:'edit',draft:{product_id:'p1',name:'Café Especial',sku:'CAF-1',minimum_stock:4},result:{version:'v1',correlation_id:'c',outcome:'Error',error:{code:'VALIDATION',message:'unidade ambígua'}}});assert.match(html,/unidade ambígua/);assert.match(html,/Café Especial/);assert.match(html,/CAF-1/);assert.match(html,/data-preserve-input="true"/);assert.match(html,/role="alert"/);});

test('manual adjustment requires reason and preserves input on semantic error',()=>{const h=harness();const html=h.ui.renderAdjustment({draft:{product_id:'p1',quantity:-3,reason:'quebra no transporte'},result:{version:'v1',correlation_id:'c',outcome:'Error',error:{code:'HEALING_REQUIRED',message:'confirmação do operador necessária'}}});assert.match(html,/quebra no transporte/);assert.match(html,/confirmação do operador necessária/);assert.match(html,/Motivo do ajuste/);assert.match(html,/required aria-required="true"/);assert.match(html,/autorização e validação semântica/);});

test('loading empty and error states are consistent',()=>{const h=harness();assert.match(h.ui.renderList({kind:'loading'}),/Carregando/);assert.match(h.ui.renderList({kind:'empty'}),/Nenhum produto/);assert.match(h.ui.renderList({kind:'error',message:'projection unavailable'}),/projection unavailable/);});

test('source does not mutate stock or recompute minimum-stock policy in browser',async()=>{const fs=await import('node:fs/promises');const source=await fs.readFile(new URL('../ui/products-inventory.ts',import.meta.url),'utf8');assert.doesNotMatch(source,/current_stock\s*[+\-]=|inventory\.set|reduce\s*\(/);assert.match(source,/ProductsInventoryProjection/);assert.match(source,/AdjustStockIntent/);});
