import test from 'node:test';import assert from 'node:assert/strict';
import {PurchasesSuppliersUi} from '../ui/purchases-suppliers.js';

function harness(){const calls:any[]=[];const api:any={query:(...args:any[])=>{calls.push(['query',...args]);return Promise.resolve({outcome:'Ok',data:{}});},command:(...args:any[])=>{calls.push(['command',...args]);return Promise.resolve({outcome:'Ok',data:{}});}};return{ui:new PurchasesSuppliersUi(api),calls};}

test('purchase supplier reads use explicit projections',async()=>{const h=harness();await h.ui.purchases({status:'pending-confirmation'},'c1');await h.ui.suppliers({},'c2');await h.ui.supplierHistory('s1','c3');await h.ui.evidence('p1','c4');assert.deepEqual(h.calls.map(c=>c[1]),['PurchasesProjection','SuppliersProjection','SupplierPurchaseHistoryProjection','PurchaseEvidenceProjection']);});
test('writes are semantic intents and purchase uses existing PurchaseProductsIntent',async()=>{const h=harness();await h.ui.savePurchase({supplier_id:'s',supplier_name:'Mercado',currency:'BRL',items:[]},'c','i');await h.ui.saveSupplier('create',{name:'Mercado'},'c2','i2');await h.ui.confirmEvidence({purchase_id:'p',evidence_id:'e',resolved_values:{total:10}},'c3','i3');assert.deepEqual(h.calls.map(c=>c[1]),['PurchaseProductsIntent','CreateSupplierIntent','ConfirmPurchaseEvidenceIntent']);});
test('purchase editor preserves draft when semantic validation fails',()=>{const h=harness();const html=h.ui.renderPurchaseEditor({draft:{supplier_id:'s1',supplier_name:'Mercado Central',currency:'BRL',items:[{product_id:'beer',name:'Beer',quantity:2,unit_price:4}]},result:{outcome:'Error',correlation_id:'c',error:{code:'validation',message:'confirme o preço'}} as any});assert.match(html,/data-preserve-input="true"/);assert.match(html,/Mercado Central/);assert.match(html,/confirme o preço/);});
test('unresolved evidence is explicitly surfaced for human confirmation',()=>{const h=harness();const html=h.ui.renderEvidence({purchase:{purchase_id:'p1',supplier_id:'s1',supplier_name:'M',at:'now',total:10,currency:'BRL',status:'pending-confirmation',evidence_count:1},items:[{evidence_id:'e1',kind:'image',source:'receipt.jpg',resolved_values:{total:10},status:'needs-confirmation'}]});assert.match(html,/confirmação humana/i);assert.match(html,/receipt.jpg/);assert.match(html,/(?:&quot;|\")total(?:&quot;|\"):10/);});
test('purchase and supplier states include loading empty and error',()=>{const h=harness();assert.match(h.ui.renderPurchases({kind:'loading'}),/Carregando/);assert.match(h.ui.renderPurchases({kind:'empty'}),/Nenhuma compra/);assert.match(h.ui.renderSuppliers({kind:'error',message:'offline'}),/offline/);});