import test from 'node:test';import assert from 'node:assert/strict';
import {RealtimeUiCoordinator,renderRealtimeNotifications,type UiSemanticEvent} from '../ui/realtime-events.js';

function event(overrides:Partial<UiSemanticEvent>={}):UiSemanticEvent{return {event_id:'e1',cursor:'10',name:'SaleUpdated',occurred_at:'now',correlation_id:'c1',severity:'info',affected_projections:['SalesProjection'],...overrides};}

test('realtime adapter resumes from stored cursor',()=>{let after:string|undefined;const transport:any={connect:(input:any)=>{after=input.after;return{close(){}};}};const cursors:any={load:()=> '42',save:()=>{}};new RealtimeUiCoordinator(transport,cursors,()=>{},()=>{}).start();assert.equal(after,'42');});
test('events invalidate only affected projections and persist cursor',()=>{let handler:any;const invalidations:any[]=[];const saved:string[]=[];const transport:any={connect:(input:any)=>{handler=input.onEvent;return{close(){}};}};const coordinator=new RealtimeUiCoordinator(transport,{load:()=>undefined,save:(c:string)=>saved.push(c)},(p,e)=>invalidations.push([p,e.event_id]),()=>{});coordinator.start();handler(event({affected_projections:['SalesProjection','CommercialDashboardProjection'],cursor:'11'}));assert.deepEqual(saved,['11']);assert.deepEqual(invalidations,[[['SalesProjection','CommercialDashboardProjection'],'e1']]);});
test('duplicate event after reconnect does not duplicate refresh or notification',()=>{const connects:any[]=[];const invalidations:any[]=[];const notices:any[]=[];let cursor:string|undefined;const transport:any={connect:(input:any)=>{connects.push(input);return{close(){}};}};const coordinator=new RealtimeUiCoordinator(transport,{load:()=>cursor,save:(c:string)=>{cursor=c}},p=>invalidations.push(p),n=>notices.push(n));coordinator.start();connects[0].onEvent(event({severity:'error',message:'Falha na venda'}));coordinator.reconnect();assert.equal(connects[1].after,'10');connects[1].onEvent(event({severity:'error',message:'Falha na venda'}));assert.equal(invalidations.length,1);assert.equal(notices.length,1);});
test('human-required and Error events become visible notifications',()=>{let handler:any;const notices:any[]=[];const transport:any={connect:(input:any)=>{handler=input.onEvent;return{close(){}};}};const coordinator=new RealtimeUiCoordinator(transport,{load:()=>undefined,save:()=>{}},()=>{},n=>notices.push(n));coordinator.start();handler(event({event_id:'h1',cursor:'1',human_required:true,message:'Confirme os produtos'}));handler(event({event_id:'x1',cursor:'2',severity:'error',message:'Pagamento divergente'}));assert.deepEqual(notices.map(n=>n.tone),['warning','danger']);const html=renderRealtimeNotifications(notices);assert.match(html,/Confirme os produtos/);assert.match(html,/Pagamento divergente/);assert.match(html,/aria-live="polite"/);});
test('transport has no domain mutation capability',async()=>{const fs=await import('node:fs/promises');const source=await fs.readFile(new URL('../ui/realtime-events.ts',import.meta.url),'utf8');assert.doesNotMatch(source,/\.command\s*\(/);assert.doesNotMatch(source,/\/v1\/intents/);assert.match(source,/affected_projections/);});