import test from 'node:test';import assert from 'node:assert/strict';
import {SalesCustomersUi} from '../ui/sales-customers.js';

function harness(){const calls:any[]=[];const api:any={query:(...args:any[])=>{calls.push(['query',...args]);return Promise.resolve({outcome:'Ok',data:{}});},command:(...args:any[])=>{calls.push(['command',...args]);return Promise.resolve({outcome:'Ok',data:{}});}};return{ui:new SalesCustomersUi(api),calls};}
const sale=(allowed_actions:any[]=[])=>({sale_id:'sale-1',at:'now',total:20,currency:'BRL',payment_state:'paid',status:'needs-products',products:[],stock_effects:[{product_id:'beer',quantity_delta:-2}],allowed_actions} as any);

test('sales and customer reads use explicit projections',async()=>{const h=harness();await h.ui.sales({status:'needs-products'},'c1');await h.ui.saleDetails('s1','c2');await h.ui.customers({},'c3');await h.ui.customerHistory('customer-1','c4');assert.deepEqual(h.calls.map(c=>c[1]),['SalesProjection','SaleDetailsProjection','CustomersProjection','CustomerPurchaseHistoryProjection']);});
test('incomplete sale resolution and customer association use existing intents',async()=>{const h=harness();await h.ui.resolveSale({sale_id:'s1',products:[{product_id:'beer',name:'Beer',quantity:2,unit_price:10}]},'c1','i1');await h.ui.associateCustomer({sale_id:'s1',customer_id:'customer-1'},'c2','i2');assert.deepEqual(h.calls.map(c=>c[1]),['ProcessSaleIntent','AssociateCustomerToSaleIntent']);});
test('customer management uses explicit semantic intents',async()=>{const h=harness();await h.ui.saveCustomer('create',{name:'Ana'},'c1','i1');await h.ui.saveCustomer('edit',{customer_id:'c1',name:'Ana'},'c2','i2');assert.deepEqual(h.calls.map(c=>c[1]),['CreateCustomerIntent','UpdateCustomerIntent']);});
test('cancel and refund are blocked unless projection explicitly permits them',async()=>{const h=harness();assert.throws(()=>h.ui.cancelSale(sale([]),'reason','c','i'),/not permitted/);assert.throws(()=>h.ui.refundSale(sale([]),'reason','c','i'),/not permitted/);await h.ui.cancelSale(sale(['cancel']),'duplicate','c2','i2');await h.ui.refundSale(sale(['refund']),'chargeback','c3','i3');assert.deepEqual(h.calls.map(c=>c[1]),['CancelSaleIntent','RefundSaleIntent']);});
test('sale details show projected payment products and stock effects',()=>{const h=harness();const html=h.ui.renderSaleDetails({...sale(['refund']),products:[{product_id:'beer',name:'Beer',quantity:2,unit_price:10}]});assert.match(html,/Pagamento: paid/);assert.match(html,/Beer/);assert.match(html,/-2/);assert.match(html,/refund/);});
test('resolution preserves draft on semantic error',()=>{const h=harness();const html=h.ui.renderResolution({draft:{sale_id:'s1',products:[{product_id:'beer',name:'Beer',quantity:2,unit_price:10}]},result:{outcome:'Error',correlation_id:'c',error:{code:'validation',message:'confirme produtos'}} as any});assert.match(html,/data-preserve-input="true"/);assert.match(html,/confirme produtos/);});
test('sales and customers expose loading empty and error states',()=>{const h=harness();assert.match(h.ui.renderSales({kind:'loading'}),/Carregando/);assert.match(h.ui.renderSales({kind:'empty'}),/Nenhuma venda/);assert.match(h.ui.renderCustomers({kind:'error',message:'offline'}),/offline/);});