import test from 'node:test';import assert from 'node:assert/strict';
import {SaleLifecycleCoordinator} from '../sales/sale-lifecycle.js';

function harness(stock:Record<string,number>={beer:5}){const effects:any[]=[];const healing:any[]=[];const audit:any[]=[];const inventory={available:async(id:string)=>stock[id]??0};const effectPort={process:async(input:any)=>{effects.push(input);for(const p of input.products)stock[p.product_id]=(stock[p.product_id]??0)-p.quantity;return{outcome:'Ok' as const};}};const healingPort={request:async(input:any)=>{healing.push(input);}};const auditPort={record:async(input:any)=>{audit.push(input);}};return{coordinator:new SaleLifecycleCoordinator(inventory,effectPort,healingPort,auditPort),stock,effects,healing,audit};}
const base={event_id:'evt-1',sale_id:'sale-1',amount:10,currency:'BRL'};

test('resolved sale validates stock, decrements once and closes',async()=>{const h=harness();const r=await h.coordinator.handle({...base,products:[{product_id:'beer',label:'Beer',quantity:2,unit_price:5}]});assert.equal(r.outcome,'Ok');assert.equal(h.stock.beer,3);assert.equal(h.effects.length,1);assert.equal(h.effects[0].idempotency_key,'sale-effect:evt-1');});
test('duplicate event returns closed result without second stock effect',async()=>{const h=harness();const event={...base,products:[{product_id:'beer',label:'Beer',quantity:1,unit_price:10}]};await h.coordinator.handle(event);const r=await h.coordinator.handle(event);assert.equal(r.outcome,'Ok');assert.equal(h.stock.beer,4);assert.equal(h.effects.length,1);assert.equal(r.outcome==='Ok'&&r.duplicate,true);});
test('unresolved products enter healing without domain effects',async()=>{const h=harness();const r=await h.coordinator.handle(base);assert.deepEqual(r,{outcome:'Pending',sale_id:'sale-1',reason:'products-unresolved'});assert.equal(h.effects.length,0);assert.equal(h.stock.beer,5);assert.equal(h.healing.length,1);});
test('insufficient stock preserves stock and financial effects',async()=>{const h=harness({beer:1});const r=await h.coordinator.handle({...base,products:[{product_id:'beer',label:'Beer',quantity:2,unit_price:5}]});assert.equal(r.outcome==='Pending'&&r.reason,'insufficient-stock');assert.equal(h.stock.beer,1);assert.equal(h.effects.length,0);});
test('fully priced products must reconcile to detected payment amount',async()=>{const h=harness();const r=await h.coordinator.handle({...base,amount:12,products:[{product_id:'beer',label:'Beer',quantity:2,unit_price:5}]});assert.equal(r.outcome==='Pending'&&r.reason,'amount-mismatch');assert.equal(h.effects.length,0);assert.equal(h.stock.beer,5);});
test('invalid quantity never reaches stock decrement',async()=>{const h=harness();const r=await h.coordinator.handle({...base,products:[{product_id:'beer',label:'Beer',quantity:0,unit_price:10}]});assert.equal(r.outcome==='Pending'&&r.reason,'invalid-products');assert.equal(h.effects.length,0);});
