import test from 'node:test';import assert from 'node:assert/strict';
import {createDeterministicSandboxState,resetSandboxState,SANDBOX_SEED_VERSION} from '../sandbox/seed.js';
import {snapshot} from '../runtime/state.js';
import {SandboxWhatsAppProvider,SandboxPaymentProvider,SandboxFiscalProvider} from '../sandbox/providers.js';

test('seed is deterministic and representative',()=>{const a=snapshot(createDeterministicSandboxState());const b=snapshot(createDeterministicSandboxState());assert.deepEqual(a,b);assert.equal(SANDBOX_SEED_VERSION,'v1');assert.ok(Object.keys(a.inventory).length>=3);assert.ok(a.purchases.length>=1);assert.ok(a.sales.length>=1);assert.ok(a.ledger.some(x=>x.kind==='purchase-expense'));assert.ok(a.ledger.some(x=>x.kind==='sale-revenue'));assert.ok(a.users.length>=2);});
test('reset returns pristine deterministic state',()=>{const state=createDeterministicSandboxState();state.inventory.set('beer-350',0);state.sales.clear();assert.deepEqual(snapshot(resetSandboxState()),snapshot(createDeterministicSandboxState()));});
test('sandbox providers are deterministic and credential-free',async()=>{const wa=new SandboxWhatsAppProvider();const inbound=wa.inbound({id:'m1',from:'5511@s.whatsapp.net',kind:'text',text:'oi'});assert.equal(inbound.instance,'sandbox');assert.deepEqual(await wa.sendText('5511','ok'),{provider_message_id:'sandbox-wa-1'});const payment=new SandboxPaymentProvider().detect({sale_id:'s1',amount:10,currency:'BRL'});assert.equal(payment.event_id,'sandbox-payment-s1');const invoice=new SandboxFiscalProvider().issue({invoice_id:'i1',sale_id:'s1',amount:10,currency:'BRL'});assert.equal(invoice.external_id,'SANDBOX-NF-i1');});
test('sandbox source uses real semantic runtime paths',async()=>{const fs=await import('node:fs/promises');const src=await fs.readFile(new URL('../runtime/sandbox-demo.ts',import.meta.url),'utf8');assert.match(src,/createExecutionKernel/);assert.match(src,/FlowRuntime/);assert.match(src,/runtime\.execute\('purchase-products'/);assert.match(src,/runtime\.execute\('process-sale'/);assert.match(src,/waiting-human/);assert.doesNotMatch(src,/state\.inventory\.set|state\.sales\.set|state\.purchases\.set/);});
