import test from 'node:test';import assert from 'node:assert/strict';import {SlidingWindowRateLimiter,ReplayGuard,assertResourceAccess,requireScope,sanitizeText,validateMediaMetadata,constantTimeSecretEqual} from '../runtime/security-hardening.js';

test('forged secrets are rejected and valid secret matches',()=>{assert.equal(constantTimeSecretEqual('forged','expected'),false);assert.equal(constantTimeSecretEqual('expected','expected'),true);});
test('replay guard rejects duplicate webhook/provider identifiers',()=>{const guard=new ReplayGuard();assert.equal(guard.accept('evt-1'),true);assert.equal(guard.accept('evt-1'),false);});
test('rate limiter blocks abuse inside the active window',()=>{const r=new SlidingWindowRateLimiter(2,1000);assert.equal(r.allow('ip',1000),true);assert.equal(r.allow('ip',1100),true);assert.equal(r.allow('ip',1200),false);assert.equal(r.allow('ip',2101),true);});
test('IDOR is denied unless operator owns resource or has admin scope',()=>{const owner={id:'u1',roles:[],scopes:[]};const other={id:'u2',roles:[],scopes:[]};const admin={id:'u2',roles:[],scopes:['resource:admin']};assert.doesNotThrow(()=>assertResourceAccess(owner,'u1'));assert.throws(()=>assertResourceAccess(other,'u1'),/Forbidden/);assert.doesNotThrow(()=>assertResourceAccess(admin,'u1'));});
test('authorization scopes are mandatory at protected boundaries',()=>{assert.doesNotThrow(()=>requireScope({id:'u',roles:[],scopes:['sales:write']},'sales:write'));assert.throws(()=>requireScope({id:'u',roles:[],scopes:[]},'sales:write'),/Forbidden/);});
test('unsafe media metadata is rejected',()=>{assert.deepEqual(validateMediaMetadata({mimetype:'application/pdf',fileLength:100,fileName:'receipt.pdf'}).mimetype,'application/pdf');assert.throws(()=>validateMediaMetadata({mimetype:'application/x-msdownload',fileLength:100,fileName:'x.exe'}),/UnsafeMediaType/);assert.throws(()=>validateMediaMetadata({mimetype:'image/jpeg',fileLength:20_000_000,fileName:'x.jpg'}),/UnsafeMediaSize/);assert.throws(()=>validateMediaMetadata({mimetype:'image/jpeg',fileLength:1,fileName:'../x.jpg'}),/UnsafeMediaFilename/);});
test('untrusted text cannot contain control-character injection and has size limits',()=>{assert.equal(sanitizeText("' OR 1=1 --"),"' OR 1=1 --");assert.throws(()=>sanitizeText('x\u0000y'),/UnsafeControlCharacter/);assert.throws(()=>sanitizeText('x'.repeat(5000)),/TextTooLarge/);});
