import test from 'node:test';import assert from 'node:assert/strict';
import {ApplicationApi} from '../api/application-api.js';
import {InMemoryConversationStore,WhatsAppConversationOrchestrator} from '../integrations/whatsapp/conversation-orchestrator.js';
const principal={id:'whatsapp',permissions:['*']};
const access={allows:()=>true};const projections={read:async()=>({})};
function api(calls:any[]){return new ApplicationApi({execute:async x=>{calls.push(x);return{outcome:'Ok' as const,data:{accepted:true}}}},projections,access)}
test('asks clarification rather than inventing operation',async()=>{const calls:any[]=[];const o=new WhatsAppConversationOrchestrator(api(calls),new InMemoryConversationStore(),principal);const r=await o.handle({message_id:'1',from:'5511',kind:'text',text:'oi'});assert.equal(r.kind,'clarification');assert.equal(calls.length,0)});
test('purchase image resolves to explicit PurchaseProductsIntent',async()=>{const calls:any[]=[];const store=new InMemoryConversationStore();const o=new WhatsAppConversationOrchestrator(api(calls),store,principal);const r=await o.handle({message_id:'2',from:'5512',kind:'image',text:'comprovante compra fornecedor'});assert.equal(r.kind,'completed');assert.equal(calls[0].intent,'PurchaseProductsIntent');assert.equal(await store.get('5512'),undefined)});
test('sale conversation persists and resumes across orchestrator instances',async()=>{const calls:any[]=[];const store=new InMemoryConversationStore();const a=new WhatsAppConversationOrchestrator(api(calls),store,principal);await a.handle({message_id:'3',from:'5513',kind:'text',text:'produtos da venda'});const b=new WhatsAppConversationOrchestrator(api(calls),store,principal);const r=await b.handle({message_id:'4',from:'5513',kind:'text',text:'2 cervejas'});assert.equal(r.kind,'completed');assert.equal(calls.at(-1).intent,'SellProductsIntent')});
test('expired state restarts resolution instead of silently resuming',async()=>{const calls:any[]=[];const store=new InMemoryConversationStore();await store.put({conversation_id:'old',peer:'5514',mode:'sale-resolution',context:{},updated_at:'2000-01-01T00:00:00Z',expires_at:'2000-01-01T00:00:01Z'});const o=new WhatsAppConversationOrchestrator(api(calls),store,principal);const r=await o.handle({message_id:'5',from:'5514',kind:'text',text:'oi'});assert.equal(r.kind,'clarification');assert.equal(calls.length,0)});
