system:
  canonical-label: commerce.simple

contexts:
  purchase: ./contexts/purchase.yml
  inventory: ./contexts/inventory.yml
  financial: ./contexts/financial.yml
  sales: ./contexts/sales.yml

flows:
  purchase-products: ./flows/purchase-products.2flow
  process-sale: ./flows/process-sale.2flow

policies:
  self-healing: enabled
  normalization:
    allowed-in:
      - validation
      - self-healing
  terminal-events:
    - Ok
    - Error
